### ISSUE TITLE
RecipeTreeViewController not picking up new handlers

### ISSUE THREAD

**Issue by gusgunn** [trailheadapps/apex-recipes#104]
Add to MetadataTriggerHandler, MDTAccountTriggerHandler, MDTSecondAccountTriggerHandler 
 * @group Trigger Recipes
 * @see TriggerHandler, AccountServiceLayer
(also MDTSecondAccountTriggerHandler is not in trigger recipes folder)

~Thanks for the awesome recipes and codelives.

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by gusgunn** [comment]
oops, raced off to get my kids on their school zoom. As I go through it I see a few other things not showing or linking - I'll fork and submit to save you the bother. Some might be stylistic choices you have made to avoid clutter - but I'll throw them on in case

**Comment by codefriar** [comment]
closed by #109
