### ISSUE TITLE
Database.enqueueBatch

### ISSUE THREAD

**Issue by noriabits** [trailheadapps/apex-recipes#120]
Hi,
I can't find any documentation on Database.enqueueBatch, is it a hidden method? :)
https://github.com/trailheadapps/apex-recipes/blob/da2bcb6fc8edd529f58eaf0f66faad54aef44122/force-app/main/default/classes/Async%20Apex%20Recipes/BatchApexRecipes.cls#L4

Cheers,

Pablo

**Comment by codefriar** [comment]
@noriabits  -  Thanks for the report. This is a bit of egg-on-my-face. In point of fact, all of the references to enqueueBatch are typos. they should all read executeBatch. I will get this fixed asap
