### ISSUE TITLE
Metadata Driven Trigger not working for custom objects.

### ISSUE THREAD

**Issue by PawelWozniak** [trailheadapps/apex-recipes#125]
### Summary

I am trying to implement Metadata Driven Trigger but found out that custom objects are stored as Id not name in custom settings.
![image](https://user-images.githubusercontent.com/5740564/115783596-554a2100-a3bd-11eb-962e-3c64c5935733.png)

It is a problem because getMetadataTriggers() has `WHERE Object__c = :this.objType` which is object name.

This test case is failing (object is created in setup and metadata records are added) 
```    @isTest
    static void testMetadataRecordsExists() {

        MetadataTriggerService mts = new MetadataTriggerService(
            'Metadata_Trigger_Example__c'
        );
        Test.startTest();
        List<Metadata_Driven_Trigger__mdt> triggers = mts.getMetadataTriggers();
        Test.stopTest();

        System.assert(
            triggers.size() > 0,
            'Expected to find metadata records'
        );
    }
```

### Steps To Reproduce:

1.  Create custom object
1.  Use it in test case
1. Test case is failing as no metadata entries were found as they have Id not object name

### Expected result

Metadata entry is found.

### Actual result

Metadata entry is not found.

**Comment by force2b** [comment]
@PawelWozniak You can query the full apiname of the object using this syntax: `Object__r.QualifiedApiName`

**Comment by PawelWozniak** [comment]
Yes, it works with that modification. Made PR.
