### ISSUE TITLE
Need to update the assert messages 

### ISSUE THREAD

**Issue by ChouTH** [trailheadapps/apex-recipes#139]
https://github.com/trailheadapps/apex-recipes/blob/8296cba2ca34fb16c6ffabf210dd87d66ce4046e/force-app/tests/Testing%20Recipes/StubExample_Tests.cls#L32

https://github.com/trailheadapps/apex-recipes/blob/8296cba2ca34fb16c6ffabf210dd87d66ce4046e/force-app/tests/Testing%20Recipes/StubExample_Tests.cls#L42

**Comment by codefriar** [comment]
@ChouTH - Just an update here. We're working out some kinks in our third-party-pr setup. Once we've gotten those worked out, this will be accepted!
