### ISSUE TITLE
Clicking "Make a suggestion on Github" button on the DMLRecipes Class Results in a 404 error

### ISSUE THREAD

**Issue by chrisbanm** [trailheadapps/apex-recipes#163]
### Summary

Clicking on the "Make a suggestion on Github" button results in a 404 page on Github.

### Steps To Reproduce:

1.  Clone the Apex-Recipes repro (I did that today)
2.  Follow the directions to install on a scratch org
3.  Open the Org and navigate to the Apex Recipes app
4.  Navigate to a Recipe (I didn't try them all but the first several recipes give the same result)
5. Click on the "Make a suggestion on Github" button

### Expected result

I should have been put in edit mode for the file of the Apex recipe of the page in Salesforce.

### Actual result

New browser tab opened up to https://github.com/trailheadapps/apex-recipes/edit/master/force-app/main/default/classes/Data%20Recipes/DMLRecipes.cls

resulted in the github 404 page.

### Additional information

Could this be a permissions issue? Perhaps this only works if I have forked the repo. However, that step was not mentioned in the Installation portion of the root repo README.md file. While that's probably an assumed step, not everyone will understand why this error came up.

**Comment by chrisbanm** [comment]
So, I forked the repo and repeated all of the steps to install Apex Recipes in a scratch org. The same result happens as the button still points to the trailheadapps/apex-recipes repo. Somehow the button needs to know to go to a forked repo so we can perform edits on our forked version and create a pull request for your repo.

**Comment by chrisbanm** [comment]
So I found the hard-coded URL for the button at line 85 of the formattedRecipeDisplay.js file in the formattedRecipeDisplay LWC. Not sure how you can have this automatically reference the repo from which it is cloned. Github Action?
But at the very least, a note about making this change should be in the README.md or CONTRIBUTION.md file.

**Comment by codefriar** [comment]
@chrisbanm  - Great find.

I've been thinking about how to fix this. 
I'm thinking we need to have a custom setting? that defines the URL path. 
If the user follows instructions and sets that custom setting, then all is good. Optionally, it can be scripted in bin/orgInit.sh

What do you think about that as a solution?

**Comment by chrisbanm** [comment]
@codefriar Outstanding! As this repo is meant for teaching Apex rather than git, sfdx, or LWC's, etc. then having a custom setting is great for most SF Admins learning Apex, but putting something into orgInit.sh would also be good. I didn't even know that was there and performed all the commands via copy and paste from the README. Now I don't have to write that myself :-)

**Comment by codefriar** [comment]
@chrisbanm  Ok, let me finish up in the branch i'm working in now, then I'll create a new one and tackle this. I'll @ you on the PR so you can kick the tires, as it were, while we work through the PR process internally.

**Comment by chrisbanm** [comment]
Outstanding all around!

*Christopher Bortz*
*Director of Information Management and Solutions*
***@***.***
540-456-7111 Ext. 174

**Comment by chrisbanm** [comment]
@codefriar I had previously forked the project and built Apex Recipes from my forked cloned to my computer. I supposed that not everyone will do that. However, if they don't, then the button shouldn't even be there as they won't be able to contribute to this repo.

**Comment by codefriar** [comment]
@chrisbanm - just a note that I'm still working out how to best tackle this

**Comment by chrisbanm** [comment]
Thanks @codefriar!

**Comment by codefriar** [comment]
@chrisbanm - just merged a PR to address this. Would love your help testing it.

As of now, the source includes a custom label, (Github_username) with a default value of 'trailheadapps'. 
When the formatted code display LWC loads, it checks that label, and if the value is 'trailheadapps' it links you to the default Contributions.md document in the Trailheadapps/apex-recipes repo.

If, however, you change that to be your OWN github username, it should link you to an edit window for your fork.

Let me know how it works for you, and if you don't have any other issues, I'll update the readme.
