### ISSUE TITLE
Reusable StripInaccessible Utility Class

### ISSUE THREAD

**Issue by borkarameya** [trailheadapps/apex-recipes#175]
The StripInaccessibleRecipes class is a really great way of understanding how things work.
Along with that, it would be really great to have a reusable StripInaccessble class that contains all DML operations.
Since, the operations will stay the same irrespective of the use case, it would make more sense to have such a class.
That way, the developer has one less thing to worry about.

For example,
`
StripInaccessible.create(accountList);
StripInaccessible.edit(accountList);
StripInaccessible.remove(accountList);
`

**Comment by codefriar** [comment]
@borkarameya thanks for filing this issue. I had the same thought about a month ago, and last week released a dedicated library that covers not only DML, but access checks in general. You can find the code, and installation/usage instructions here: https://github.com/codefriar/CanTheUser Note you'll want to specifically look at the Safely side of things. ie: Safely.insert(...) etc.
