### ISSUE TITLE
Package ApexRecipes Install Failed

### ISSUE THREAD

**Issue by Josecjr** [trailheadapps/apex-recipes#22]
### Summary

Package ApexRecipes Install Failed

### Steps To Reproduce:

1)Log in to your org

2)f you are setting up a Developer Edition: go to Setup, under My Domain, register a My Domain.

3)Please be sure that the domain is both registered and deployed and that your user has logged into the new domain.
4)Go to Setup, under Platform Cache, and click the "Request Trial Capacity" button. Request a Platform Cache Trial

5)Click this link to install the Apex Recipes unlocked package in your org.

6)Select Install for All Users

### Expected result

Package installed

### Actual result

Your request to install package "ApexRecipes Winter '21 release" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: HarpiaCloud (00Df4000002cmIj)
User: Jose Costa (005f4000000cRaq)
Package: ApexRecipes (04t3g000000ki8s)
Error Number: 1645147636-198382 (1630339717)

Problem:

1.  Permission Read Account depends on permission(s): Read Contact
Provides_Edit_Access_to_Accounts_Except_ShippingStreet: Permission Read Account depends on permission(s): Read Contact

2.  Permission Read Account depends on permission(s): Read Contact
Provides_Read_Only_Access_to_Account_and_All_Fields: Permission Read Account depends on permission(s): Read Contact

3.  Permission Read Account depends on permission(s): Read Contact
Proving_With_Security_Enforced_Works: Permission Read Account depends on permission(s): Read Contact

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by codefriar** [comment]
@Josecjr - Can you try the latest package version please?

**Comment by Josecjr** [comment]
Same error. I've used this one: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3g000000ki9CAAQ

**Comment by Josecjr** [comment]
Your request to install package "ApexRecipes Winter '21 release" was
unsuccessful. None of the data or setup information in your
salesforce.com organization
was affected.

If your install continues to fail, contact Salesforce CRM Support through
your normal channels and provide the following information.

Organization: HarpiaCloud (00Df4000002cmIj)
User: Jose Costa (005f4000000cRaq)
Package: ApexRecipes (04t3g000000ki9C)
Error Number: 300611045-38708 (1630339717)
Ocultar texto das mensagens anteriores

Problem:

1.  Permission Read Account depends on permission(s): Read Contact
Provides_Edit_Access_to_Accounts_Except_ShippingStreet: Permission Read
Account depends on permission(s): Read Contact

2.  Permission Read Account depends on permission(s): Read Contact
Provides_Read_Only_Access_to_Account_and_All_Fields: Permission Read
Account depends on permission(s): Read Contact

3.  Permission Read Account depends on permission(s): Read Contact
Proving_With_Security_Enforced_Works: Permission Read Account depends on
permission(s): Read Contact

Em seg., 19 de out. de 2020 10:15 PM, Kevin Poorman <
notifications@github.com> escreveu:

**Comment by codefriar** [comment]
@Josecjr - I just spun up a new de org and installed the package just fine. I used this installation link: https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3g000000ki9CAAQ

Is it possible you're installing it in an org that has pre-existing modifications?

**Comment by Josecjr** [comment]
The same.. that is weird... My org is a Partner Dev Org (the one with more
limits) with some low level customizations.

Organization: HarpiaCloud (00Df4000002cmIj)
User: Jose Costa (005f4000000cRaq)
Package: ApexRecipes (04t3g000000ki9C)
Error Number: 348708159-32495 (1630339717)
Problem:

1.  Permission Read Account depends on permission(s): Read Contact
Provides_Edit_Access_to_Accounts_Except_ShippingStreet: Permission Read
Account depends on permission(s): Read Contact

2.  Permission Read Account depends on permission(s): Read Contact
Provides_Read_Only_Access_to_Account_and_All_Fields: Permission Read
Account depends on permission(s): Read Contact

3.  Permission Read Account depends on permission(s): Read Contact
Proving_With_Security_Enforced_Works: Permission Read Account depends on
permission(s): Read Contact
José Costa Junior


Em qua., 21 de out. de 2020 às 09:29, Kevin Poorman <
notifications@github.com> escreveu:

**Comment by codefriar** [comment]
Mind trying in a standard DE org, or Partner org with no modifications?

**Comment by Josecjr** [comment]
In a new sandbox it worked.
José Costa Junior


Em qua., 21 de out. de 2020 às 10:49, Kevin Poorman <
notifications@github.com> escreveu:

**Comment by sfdcschwabe** [comment]
I've got the same problem on an existing Sandbox:

Your request to install package "ApexRecipes Winter '21 release" was successful.

Organization: Heiko Kraemer (00D0Q0000001Csw)
User: Christian Schwabe (0057R00000At4tG)
Package: ApexRecipes (04t3g000000kiDJ)

Some components, such as custom objects, custom report types, and workflow rules, must be activated using the package deploy process, before they are available to your organization.


Did you find out the reason?

**Comment by sfdcschwabe** [comment]
I've tried to install the unlocked package 'Apex Recipes' with this link 'https://test.salesforce.com/packaging/installPackage.apexp?p0=04t3g000000kiDJAAY' on one of our sandboxes and get the following error:

Organization: Colliers International Deutschland GmbH (00D0E0000002LcN)
User: Christian Schwabe (0050O000009pHg3)
Package: ApexRecipes (04t3g000000kiDJ)
Error Number: 752431791-1832068 (1903002296)
Problem:

1.  Permission Read Account depends on permission(s): Read Contact
Provides_Edit_Access_to_Accounts_Except_ShippingStreet: Permission Read Account depends on permission(s): Read Contact

2.  Permission Read Account depends on permission(s): Read Contact
Provides_Read_Only_Access_to_Account_and_All_Fields: Permission Read Account depends on permission(s): Read Contact

3.  Permission Read Account depends on permission(s): Read Contact
Proving_With_Security_Enforced_Works: Permission Read Account depends on permission(s): Read Contact
