### ISSUE TITLE
Email Recipe Updates

### ISSUE THREAD

**Issue by jkranz-rk** [trailheadapps/apex-recipes#267]
### Summary

The Email Recipe shows creating an `EmailMessage` with a status of `0`. When people are looking for guidance on how to create `EmailMessage`s, this will lead them in a confusing direction, as any `EmailMessage`s that are created with this status will appear in the "Upcoming and Overdue" portion of the Activity Timeline instead of in the Activity History based on the day/time of the email. Setting the status to `3` resolves that behavior. The documentation isn't very clear about this, so I think demonstrating it in the recipe would help a lot of people.

In addition, I think it would be helpful if the recipe shows the `IsClientManaged` field, as this is what would allow adding files to the Email in a way that will surface the attachment Icon in the Activity timeline.

### Suggested Solution

When inserting the EmailMessage, set the `Status` field to `3` instead of `0`

When inserting the EmailMessage, add the `IsClientManaged` field, setting it to `true`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codefriar** [comment]
@jkranz-rk Thanks for this issue and your PR. Due to the way our CI system works, I've re-implemented the changes in #270
