### ISSUE TITLE
Error retrieving data - (Regex too complicated)

### ISSUE THREAD

**Issue by Yasir-Sheriff** [trailheadapps/apex-recipes#37]
### Summary

_Short summary of what is going on or to provide context_.
![image](https://user-images.githubusercontent.com/52495811/99268098-c142bf00-284a-11eb-803e-3b0088d54857.png)

### Additional information

`50.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
06:40:46.0 (191358)|USER_INFO|[EXTERNAL]|0052y000001TLcZ|yasirsherifff@gmail.com.dev|(GMT-08:00) Pacific Standard Time (America/Los_Angeles)|GMT-08:00
06:40:46.0 (240841)|EXECUTION_STARTED
06:40:46.0 (246604)|CODE_UNIT_STARTED|[EXTERNAL]|apex://RecipeTreeViewController/ACTION$generateTreeData
06:40:46.0 (933339)|CODE_UNIT_STARTED|[EXTERNAL]|01p2y000001aEkr|RecipeTreeViewController.generateTreeData()
06:40:46.0 (1020339)|VARIABLE_SCOPE_BEGIN|[14]|RecipeTreeViewController.APEXRECIPESIDENTIFICATIONTAG|String|false|true
06:40:46.0 (1060067)|VARIABLE_SCOPE_BEGIN|[8]|RecipeTreeViewController.groupToListOfNames|Map<String,List<String>>|true|true
06:40:46.0 (1213393)|HEAP_ALLOCATE|[79]|Bytes:3
06:40:46.0 (1268071)|HEAP_ALLOCATE|[84]|Bytes:152
06:40:46.0 (1286636)|HEAP_ALLOCATE|[399]|Bytes:408
06:40:46.0 (1304682)|HEAP_ALLOCATE|[412]|Bytes:408
06:40:46.0 (1320315)|HEAP_ALLOCATE|[520]|Bytes:48
06:40:46.0 (1348901)|HEAP_ALLOCATE|[139]|Bytes:6
06:40:46.0 (1373248)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:14
06:40:46.0 (1381950)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:6
06:40:46.0 (1387188)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
06:40:46.0 (1444839)|VARIABLE_ASSIGNMENT|[EXTERNAL]|RecipeTreeViewController.APEXRECIPESIDENTIFICATIONTAG|"* @group"
06:40:46.0 (1464414)|METHOD_ENTRY|[7]|01p2y000001aEkr|RecipeTreeViewController.RecipeTreeViewController()
06:40:46.0 (1474224)|STATEMENT_EXECUTE|[7]
06:40:46.0 (1481525)|STATEMENT_EXECUTE|[7]
06:40:46.0 (1543331)|HEAP_ALLOCATE|[52]|Bytes:5
06:40:46.0 (1571462)|HEAP_ALLOCATE|[58]|Bytes:5
06:40:46.0 (1582924)|HEAP_ALLOCATE|[66]|Bytes:7
06:40:46.0 (1618331)|SYSTEM_MODE_ENTER|false
06:40:46.0 (1638107)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:5
06:40:46.0 (1645811)|STATEMENT_EXECUTE|[20]
06:40:46.0 (1653064)|SYSTEM_MODE_EXIT|false
06:40:46.0 (1665054)|METHOD_EXIT|[7]|RecipeTreeViewController
06:40:46.0 (1674516)|SYSTEM_MODE_ENTER|false
06:40:46.0 (1690171)|HEAP_ALLOCATE|[59]|Bytes:5
06:40:46.0 (1697664)|STATEMENT_EXECUTE|[58]
06:40:46.0 (1700658)|STATEMENT_EXECUTE|[59]
06:40:46.0 (1717625)|HEAP_ALLOCATE|[59]|Bytes:4
06:40:46.0 (1816160)|VARIABLE_SCOPE_BEGIN|[59]|treeData|List<RecipeTreeViewController.RecipeTreeData>|true|false
06:40:46.0 (1851059)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
06:40:46.0 (1872483)|VARIABLE_ASSIGNMENT|[59]|treeData|[]|0x44b4ea88
06:40:46.0 (1881670)|STATEMENT_EXECUTE|[60]
06:40:46.0 (1961135)|HEAP_ALLOCATE|[60]|Bytes:2
06:40:46.0 (1984511)|HEAP_ALLOCATE|[60]|Bytes:20
06:40:46.0 (1997077)|CONSTRUCTOR_ENTRY|[60]|01p2y000001aEkr|<init>()|RecipeTreeViewController.RecipeTreeData
06:40:46.0 (2024882)|VARIABLE_SCOPE_BEGIN|[20]|this|RecipeTreeViewController.RecipeTreeData|true|false
06:40:46.0 (2074545)|VARIABLE_ASSIGNMENT|[20]|this|{}|0x24ad1939
06:40:46.0 (2089382)|HEAP_ALLOCATE|[26]|Bytes:6
06:40:46.0 (3970864)|STATEMENT_EXECUTE|[20]
06:40:46.0 (3979537)|STATEMENT_EXECUTE|[22]
06:40:46.0 (3984340)|STATEMENT_EXECUTE|[24]
06:40:46.0 (3988029)|STATEMENT_EXECUTE|[26]
06:40:46.0 (4004778)|HEAP_ALLOCATE|[26]|Bytes:5
06:40:46.0 (4032390)|VARIABLE_ASSIGNMENT|[26]|this.expanded|false|0x24ad1939
06:40:46.0 (4045077)|STATEMENT_EXECUTE|[28]
06:40:46.0 (4055683)|CONSTRUCTOR_EXIT|[60]|01p2y000001aEkr|<init>()|RecipeTreeViewController.RecipeTreeData
06:40:46.0 (4070624)|VARIABLE_SCOPE_BEGIN|[60]|recipes|RecipeTreeViewController.RecipeTreeData|true|false
06:40:46.0 (4110438)|VARIABLE_ASSIGNMENT|[60]|recipes|{"expanded":false}|0x24ad1939
06:40:46.0 (4120087)|STATEMENT_EXECUTE|[61]
06:40:46.0 (4127285)|HEAP_ALLOCATE|[61]|Bytes:7
06:40:46.0 (4142786)|VARIABLE_ASSIGNMENT|[61]|this.label|"Recipes"|0x24ad1939
06:40:46.0 (4153704)|STATEMENT_EXECUTE|[62]
06:40:46.0 (4168617)|VARIABLE_ASSIGNMENT|[62]|this.name|"Recipes"|0x24ad1939
06:40:46.0 (4181100)|STATEMENT_EXECUTE|[63]
06:40:46.0 (4190077)|HEAP_ALLOCATE|[63]|Bytes:5
06:40:46.0 (4202203)|VARIABLE_ASSIGNMENT|[63]|this.expanded|true|0x24ad1939
06:40:46.0 (4216386)|STATEMENT_EXECUTE|[64]
06:40:46.0 (4237764)|HEAP_ALLOCATE|[64]|Bytes:4
06:40:46.0 (4304487)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
06:40:46.0 (4321187)|VARIABLE_ASSIGNMENT|[64]|this.items|[]|0x24ad1939
06:40:46.0 (4332548)|STATEMENT_EXECUTE|[65]
06:40:46.0 (4338459)|HEAP_ALLOCATE|[65]|Bytes:20
06:40:46.0 (4350556)|CONSTRUCTOR_ENTRY|[65]|01p2y000001aEkr|<init>()|RecipeTreeViewController.RecipeTreeData
06:40:46.0 (4372776)|VARIABLE_SCOPE_BEGIN|[20]|this|RecipeTreeViewController.RecipeTreeData|true|false
06:40:46.0 (4398880)|VARIABLE_ASSIGNMENT|[20]|this|{}|0x1f7e6d5e
06:40:46.0 (4424341)|STATEMENT_EXECUTE|[20]
06:40:46.0 (4427277)|STATEMENT_EXECUTE|[22]
06:40:46.0 (4429944)|STATEMENT_EXECUTE|[24]
06:40:46.0 (4432559)|STATEMENT_EXECUTE|[26]
06:40:46.0 (4440378)|HEAP_ALLOCATE|[26]|Bytes:5
06:40:46.0 (4449841)|VARIABLE_ASSIGNMENT|[26]|this.expanded|false|0x1f7e6d5e
06:40:46.0 (4460383)|STATEMENT_EXECUTE|[28]
06:40:46.0 (4465611)|CONSTRUCTOR_EXIT|[65]|01p2y000001aEkr|<init>()|RecipeTreeViewController.RecipeTreeData
06:40:46.0 (4477419)|VARIABLE_SCOPE_BEGIN|[65]|sharedCode|RecipeTreeViewController.RecipeTreeData|true|false
06:40:46.0 (4501149)|VARIABLE_ASSIGNMENT|[65]|sharedCode|{"expanded":false}|0x1f7e6d5e
06:40:46.0 (4511658)|STATEMENT_EXECUTE|[66]
06:40:46.0 (4528628)|METHOD_ENTRY|[66]|01p2y000001aEkr|RecipeTreeViewController.generateMapOfGroupToListOfNames()
06:40:46.0 (4563611)|HEAP_ALLOCATE|[111]|Bytes:5
06:40:46.0 (4571937)|STATEMENT_EXECUTE|[110]
06:40:46.0 (4574900)|STATEMENT_EXECUTE|[111]
06:40:46.0 (4594799)|HEAP_ALLOCATE|[111]|Bytes:4
06:40:46.0 (4616720)|VARIABLE_SCOPE_BEGIN|[111]|returnMap|Map<String,List<String>>|true|false
06:40:46.0 (4642109)|VARIABLE_ASSIGNMENT|[111]|returnMap|{}|0x7a0cdd4
06:40:46.0 (4653199)|STATEMENT_EXECUTE|[112]
06:40:46.0 (4657487)|HEAP_ALLOCATE|[112]|Bytes:59
06:40:46.0 (4673863)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (4684231)|HEAP_ALLOCATE|[112]|Bytes:7
06:40:46.0 (5134744)|SOSL_EXECUTE_BEGIN|[112]|FIND :tmpVar1 IN ALL FIELDS RETURNING apexclass(Name, Body)
06:40:46.0 (135769179)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135786098)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135794288)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135800812)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135804851)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135811117)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135817177)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135821209)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135827346)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135833941)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135840734)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135844820)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135851260)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135857208)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135863440)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135867412)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135874172)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135880053)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135884099)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135890280)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135896346)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135902684)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135906514)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135912814)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135918824)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135922679)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135928814)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135934687)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135938631)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135944485)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135950684)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135956665)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135962646)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135966526)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135972669)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135978728)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135982614)|HEAP_ALLOCATE|[112]|Bytes:4
06:40:46.0 (135993974)|HEAP_ALLOCATE|[112]|Bytes:8
06:40:46.0 (136022383)|SOSL_EXECUTE_END|[112]|Rows:36
06:40:46.0 (136107691)|HEAP_ALLOCATE|[112]|Bytes:8
06:40:46.0 (136136546)|VARIABLE_SCOPE_BEGIN|[112]|searchResults|List<List<SObject>>|true|false
06:40:46.0 (136187065)|VARIABLE_ASSIGNMENT|[112]|searchResults|["List of size 36 too large to display"]|0x635c0aac
06:40:46.0 (136202923)|STATEMENT_EXECUTE|[117]
06:40:46.0 (136297365)|HEAP_ALLOCATE|[117]|Bytes:148
06:40:46.0 (136346793)|VARIABLE_SCOPE_BEGIN|[117]|classes|List<ApexClass>|true|false
06:40:46.0 (136369664)|VARIABLE_ASSIGNMENT|[117]|classes|"List of size 36 too large to display"|0x26cd0d5a
06:40:46.0 (136641499)|HEAP_ALLOCATE|[119]|Bytes:5
06:40:46.0 (136695626)|HEAP_ALLOCATE|[119]|Bytes:16
06:40:46.0 (136710160)|VARIABLE_SCOPE_BEGIN|[119]|klass|ApexClass|true|false
06:40:46.0 (136751999)|VARIABLE_ASSIGNMENT|[119]|klass|{"Name":"ApexClassUtilities","Body":"/**\n * @description  (2444 more) ...","Id":"01p2y000001aEk2AAE"}|0x200cb542
06:40:46.0 (136764591)|STATEMENT_EXECUTE|[119]
06:40:46.0 (136767495)|STATEMENT_EXECUTE|[120]
06:40:46.0 (151990252)|HEAP_ALLOCATE|[120]|Bytes:5
06:40:46.0 (152014819)|HEAP_ALLOCATE|[120]|Bytes:17
06:40:46.0 (152041751)|METHOD_ENTRY|[8]|01p2y000001aEk2|ApexClassUtilities.ApexClassUtilities()
06:40:46.0 (152053467)|STATEMENT_EXECUTE|[8]
06:40:46.0 (152060876)|STATEMENT_EXECUTE|[8]
06:40:46.0 (152081168)|HEAP_ALLOCATE|[120]|Bytes:5
06:40:46.0 (152099200)|METHOD_EXIT|[8]|ApexClassUtilities
06:40:46.0 (152140308)|METHOD_ENTRY|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (152182058)|VARIABLE_SCOPE_BEGIN|[19]|klass|ApexClass|true|false
06:40:46.0 (152235935)|VARIABLE_ASSIGNMENT|[19]|klass|{"Name":"ApexClassUtilities","Body":"/**\n * @description  (2444 more) ...","Id":"01p2y000001aEk2AAE"}|0x200cb542
06:40:46.0 (152254464)|HEAP_ALLOCATE|[21]|Bytes:5
06:40:46.0 (152263386)|STATEMENT_EXECUTE|[19]
06:40:46.0 (152266369)|STATEMENT_EXECUTE|[20]
06:40:46.0 (152271573)|HEAP_ALLOCATE|[21]|Bytes:13
06:40:46.0 (152337577)|HEAP_ALLOCATE|[20]|Bytes:24
06:40:46.0 (152350597)|SYSTEM_METHOD_ENTRY|[1]|Pattern.Pattern()
06:40:46.0 (152357844)|STATEMENT_EXECUTE|[1]
06:40:46.0 (152364872)|SYSTEM_METHOD_EXIT|[1]|Pattern
06:40:46.0 (152379741)|METHOD_ENTRY|[20]||System.Pattern.compile(String)
06:40:46.0 (152556802)|METHOD_EXIT|[20]||System.Pattern.compile(String)
06:40:46.0 (152568173)|VARIABLE_SCOPE_BEGIN|[20]|patternForFindingGroupTagInHeader|System.Pattern|true|false
06:40:46.0 (152615101)|VARIABLE_ASSIGNMENT|[20]|patternForFindingGroupTagInHeader|{"delegate":"0x7df81df5"}|0x41555909
06:40:46.0 (152626988)|STATEMENT_EXECUTE|[23]
06:40:46.0 (152686432)|METHOD_ENTRY|[23]||System.Pattern.matcher(String)
06:40:46.0 (152920000)|METHOD_EXIT|[23]||System.Pattern.matcher(String)
06:40:46.0 (152930551)|VARIABLE_SCOPE_BEGIN|[23]|matcher|System.Matcher|true|false
06:40:46.0 (152964593)|VARIABLE_ASSIGNMENT|[23]|matcher|{"delegate":"0x51adc176"}|0x7eefee8
06:40:46.0 (152975274)|STATEMENT_EXECUTE|[24]
06:40:46.0 (152991386)|METHOD_ENTRY|[24]||System.Matcher.find()
06:40:46.0 (154838781)|METHOD_EXIT|[24]||System.Matcher.find()
06:40:46.0 (154865873)|STATEMENT_EXECUTE|[25]
06:40:46.0 (154884201)|VARIABLE_SCOPE_BEGIN|[25]|groupName|String|false|false
06:40:46.0 (154909451)|VARIABLE_ASSIGNMENT|[25]|groupName|""
06:40:46.0 (154919843)|STATEMENT_EXECUTE|[26]
06:40:46.0 (154923109)|STATEMENT_EXECUTE|[26]
06:40:46.0 (154925786)|STATEMENT_EXECUTE|[27]
06:40:46.0 (154941798)|METHOD_ENTRY|[27]||System.Matcher.group(Integer)
06:40:46.0 (155053144)|METHOD_EXIT|[27]||System.Matcher.group(Integer)
06:40:46.0 (155068867)|VARIABLE_ASSIGNMENT|[27]|groupName|"Shared Code"
06:40:46.0 (155077651)|STATEMENT_EXECUTE|[35]
06:40:46.0 (155086540)|METHOD_EXIT|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (155095421)|VARIABLE_SCOPE_BEGIN|[120]|groupName|String|false|false
06:40:46.0 (155113973)|VARIABLE_ASSIGNMENT|[120]|groupName|"Shared Code"
06:40:46.0 (155184713)|HEAP_ALLOCATE|[121]|Bytes:4
06:40:46.0 (155215122)|STATEMENT_EXECUTE|[123]
06:40:46.0 (155220346)|STATEMENT_EXECUTE|[124]
06:40:46.0 (155240586)|HEAP_ALLOCATE|[124]|Bytes:4
06:40:46.0 (155342581)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
06:40:46.0 (155352156)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:-4
06:40:46.0 (155382577)|HEAP_ALLOCATE|[119]|Bytes:5
06:40:46.0 (155404312)|HEAP_ALLOCATE|[119]|Bytes:16
06:40:46.0 (155417321)|VARIABLE_SCOPE_BEGIN|[119]|klass|ApexClass|true|false
06:40:46.0 (155454803)|VARIABLE_ASSIGNMENT|[119]|klass|{"Name":"RecipeTreeViewContro (4 more) ...","Body":"/**\n * @description  (4870 more) ...","Id":"01p2y000001aEkrAAE"}|0x17c00562
06:40:46.0 (155467940)|STATEMENT_EXECUTE|[119]
06:40:46.0 (155470792)|STATEMENT_EXECUTE|[120]
06:40:46.0 (155480019)|METHOD_ENTRY|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (155489105)|VARIABLE_SCOPE_BEGIN|[19]|klass|ApexClass|true|false
06:40:46.0 (155513015)|VARIABLE_ASSIGNMENT|[19]|klass|{"Name":"RecipeTreeViewContro (4 more) ...","Body":"/**\n * @description  (4870 more) ...","Id":"01p2y000001aEkrAAE"}|0x17c00562
06:40:46.0 (155529243)|HEAP_ALLOCATE|[21]|Bytes:5
06:40:46.0 (155536356)|STATEMENT_EXECUTE|[19]
06:40:46.0 (155539261)|STATEMENT_EXECUTE|[20]
06:40:46.0 (155546658)|METHOD_ENTRY|[20]||System.Pattern.compile(String)
06:40:46.0 (155629526)|METHOD_EXIT|[20]||System.Pattern.compile(String)
06:40:46.0 (155637718)|VARIABLE_SCOPE_BEGIN|[20]|patternForFindingGroupTagInHeader|System.Pattern|true|false
06:40:46.0 (155669386)|VARIABLE_ASSIGNMENT|[20]|patternForFindingGroupTagInHeader|{"delegate":"0x7df81df5"}|0xae86875
06:40:46.0 (155678384)|STATEMENT_EXECUTE|[23]
06:40:46.0 (155693389)|METHOD_ENTRY|[23]||System.Pattern.matcher(String)
06:40:46.0 (155784182)|METHOD_EXIT|[23]||System.Pattern.matcher(String)
06:40:46.0 (155798201)|VARIABLE_SCOPE_BEGIN|[23]|matcher|System.Matcher|true|false
06:40:46.0 (155840397)|VARIABLE_ASSIGNMENT|[23]|matcher|{"delegate":"0x660a71d8"}|0x37a3a833
06:40:46.0 (155850379)|STATEMENT_EXECUTE|[24]
06:40:46.0 (155858861)|METHOD_ENTRY|[24]||System.Matcher.find()
06:40:46.0 (156119324)|METHOD_EXIT|[24]||System.Matcher.find()
06:40:46.0 (156125181)|STATEMENT_EXECUTE|[25]
06:40:46.0 (156132213)|VARIABLE_SCOPE_BEGIN|[25]|groupName|String|false|false
06:40:46.0 (156147613)|VARIABLE_ASSIGNMENT|[25]|groupName|""
06:40:46.0 (156154081)|STATEMENT_EXECUTE|[26]
06:40:46.0 (156156618)|STATEMENT_EXECUTE|[26]
06:40:46.0 (156159009)|STATEMENT_EXECUTE|[27]
06:40:46.0 (156166442)|METHOD_ENTRY|[27]||System.Matcher.group(Integer)
06:40:46.0 (156200081)|METHOD_EXIT|[27]||System.Matcher.group(Integer)
06:40:46.0 (156209945)|VARIABLE_ASSIGNMENT|[27]|groupName|"Shared Code"
06:40:46.0 (156217063)|STATEMENT_EXECUTE|[35]
06:40:46.0 (156223346)|METHOD_EXIT|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (156233195)|VARIABLE_SCOPE_BEGIN|[120]|groupName|String|false|false
06:40:46.0 (156247311)|VARIABLE_ASSIGNMENT|[120]|groupName|"Shared Code"
06:40:46.0 (156276024)|HEAP_ALLOCATE|[121]|Bytes:19
06:40:46.0 (156296554)|STATEMENT_EXECUTE|[121]
06:40:46.0 (156299239)|STATEMENT_EXECUTE|[122]
06:40:46.0 (156368401)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
06:40:46.0 (156388172)|HEAP_ALLOCATE|[119]|Bytes:5
06:40:46.0 (156404143)|HEAP_ALLOCATE|[119]|Bytes:16
06:40:46.0 (156413747)|VARIABLE_SCOPE_BEGIN|[119]|klass|ApexClass|true|false
06:40:46.0 (156442463)|VARIABLE_ASSIGNMENT|[119]|klass|{"Name":"ConnectApiHelper","Body":"/*\r\nCopyright (c) 20 (20782 more) ...","Id":"01p2y000001aEmdAAE"}|0x2cc44a6a
06:40:46.0 (156452778)|STATEMENT_EXECUTE|[119]
06:40:46.0 (156455237)|STATEMENT_EXECUTE|[120]
06:40:46.0 (156460408)|METHOD_ENTRY|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (156470118)|VARIABLE_SCOPE_BEGIN|[19]|klass|ApexClass|true|false
06:40:46.0 (156490290)|VARIABLE_ASSIGNMENT|[19]|klass|{"Name":"ConnectApiHelper","Body":"/*\r\nCopyright (c) 20 (20782 more) ...","Id":"01p2y000001aEmdAAE"}|0x2cc44a6a
06:40:46.0 (156504319)|HEAP_ALLOCATE|[21]|Bytes:5
06:40:46.0 (156509051)|STATEMENT_EXECUTE|[19]
06:40:46.0 (156511459)|STATEMENT_EXECUTE|[20]
06:40:46.0 (156518506)|METHOD_ENTRY|[20]||System.Pattern.compile(String)
06:40:46.0 (156575354)|METHOD_EXIT|[20]||System.Pattern.compile(String)
06:40:46.0 (156580483)|VARIABLE_SCOPE_BEGIN|[20]|patternForFindingGroupTagInHeader|System.Pattern|true|false
06:40:46.0 (156605031)|VARIABLE_ASSIGNMENT|[20]|patternForFindingGroupTagInHeader|{"delegate":"0x7df81df5"}|0x2c8155b3
06:40:46.0 (156622289)|STATEMENT_EXECUTE|[23]
06:40:46.0 (156648650)|METHOD_ENTRY|[23]||System.Pattern.matcher(String)
06:40:46.0 (156717622)|METHOD_EXIT|[23]||System.Pattern.matcher(String)
06:40:46.0 (156723244)|VARIABLE_SCOPE_BEGIN|[23]|matcher|System.Matcher|true|false
06:40:46.0 (156746630)|VARIABLE_ASSIGNMENT|[23]|matcher|{"delegate":"0x108be1e4"}|0x40e99fe9
06:40:46.0 (156756890)|STATEMENT_EXECUTE|[24]
06:40:46.0 (156761554)|METHOD_ENTRY|[24]||System.Matcher.find()
06:40:46.0 (176195575)|METHOD_EXIT|[24]||System.Matcher.find()
06:40:46.0 (176220490)|METHOD_EXIT|[120]|01p2y000001aEk2|ApexClassUtilities.getGroupFromClassBody(ApexClass)
06:40:46.0 (176233442)|METHOD_EXIT|[66]|01p2y000001aEkr|RecipeTreeViewController.generateMapOfGroupToListOfNames()
06:40:46.0 (176356980)|FATAL_ERROR|System.LimitException: Regex too complicated

Class.System.Matcher.find: line 26, column 1
Class.ApexClassUtilities.getGroupFromClassBody: line 24, column 1
Class.RecipeTreeViewController.generateMapOfGroupToListOfNames: line 120, column 1
Class.RecipeTreeViewController.generateTreeData: line 66, column 1
06:40:46.0 (176374412)|FATAL_ERROR|System.LimitException: Regex too complicated

Class.System.Matcher.find: line 26, column 1
Class.ApexClassUtilities.getGroupFromClassBody: line 24, column 1
Class.RecipeTreeViewController.generateMapOfGroupToListOfNames: line 120, column 1
Class.RecipeTreeViewController.generateTreeData: line 66, column 1
06:40:46.176 (176385547)|CUMULATIVE_LIMIT_USAGE
06:40:46.176 (176385547)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 0 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 1 out of 20
  Number of DML statements: 0 out of 0
  Number of Publish Immediate DML: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

06:40:46.176 (176385547)|CUMULATIVE_LIMIT_USAGE_END

06:40:46.0 (176451607)|CODE_UNIT_FINISHED|RecipeTreeViewController.generateTreeData()
06:40:46.0 (176701543)|CODE_UNIT_FINISHED|apex://RecipeTreeViewController/ACTION$generateTreeData
06:40:46.0 (176711124)|EXECUTION_FINISHED
`

**Comment by codefriar** [comment]
@Yasir-Sheriff  

This typically occurs when users install Apex-Recpies in an org that *already* has classes and metadata installed. Please try installing in a brand new Dev, or Scratch org.

**Comment by Yasir-Sheriff** [comment]
Hello @codefriar 

I already try to lots of new developer edition org, but I've got the same issues in all org

First I install LWC recipes then try to install apex recipes that time I've got the issues

So I changed the order of installation first I try to the apex recipes is working fine

Note: Finally I've deployed the apex recipes in my developer org
