### ISSUE TITLE
Naming convention question

### ISSUE THREAD

**Issue by ChouTH** [trailheadapps/apex-recipes#38]
Since there is a `FLSType`, why using `CrudType` instead of `CRUDType`, 

When should we use camel case and when should we use all caps?

https://github.com/trailheadapps/apex-recipes/blob/7a9a4f0e26d5a302a69d98081f056a4782253249/force-app/main/default/classes/Security%20Recipes/CanTheUser.cls#L23

https://github.com/trailheadapps/apex-recipes/blob/7a9a4f0e26d5a302a69d98081f056a4782253249/force-app/main/default/classes/Security%20Recipes/CanTheUser.cls#L30

**Comment by codefriar** [comment]
@ChouTH - Good catch. I'll be updating CrudType to CRUDType here in a few minutes.
