### ISSUE TITLE
System.ListException: List index out of bounds: 0

### ISSUE THREAD

**Issue by sfdcschwabe** [trailheadapps/apex-recipes#40]
### Summary

Some kind of missing exception handling. To be honest I have no suggested solution for this. Perhaps I do something wrong with your shared code.

### Steps To Reproduce:

When you try this block of code you get an System.ListException on Class.CollectionUtils.stringMapFromCollectionByKey: line 67, column 1
```apex
List<Account> listOfAccount = new List<Account>();
//listOfAccount.add(new Account(Id = '0010E000010qaeaQAA'));
Map<String, Account> mapOfAccountById = (Map<String, Account>) CollectionUtils.stringMapFromCollectionByKey('Id', listOfAccount);
```

When you try this block of code everything works fine:
```apex
List<Account> listOfAccount = new List<Account>();
listOfAccount.add(new Account(Id = '0010E000010qaeaQAA'));
Map<String, Account> mapOfAccountById = (Map<String, Account>) CollectionUtils.stringMapFromCollectionByKey('Id', listOfAccount);
```

### Expected result

Return an empty map without exception.

### Actual result

System.ListException occurred.

### Additional information

This error occurred to me during soql queries with no results.

**Comment by codefriar** [comment]
@sfdcschwabe - can you update your code examples? They both appear identical...

**Comment by sfdcschwabe** [comment]
@codefriar 
No, they are not exact identical. One significant line is different.

**Comment by smartinello1** [comment]
The problem is that in CollectionUtils.cls there isn't a check if the list passed to the method stringMapFromCollectionByKey is empty, check line 66 in CollectionUtils.cls.

Also the other methods of the class have the same issue.

![Schermata 2020-12-02 alle 23 03 52](https://user-images.githubusercontent.com/24750230/100937018-a92d9980-34f2-11eb-965b-fe08cd8c7a60.png)

**Comment by sfdcschwabe** [comment]
@codefriar 
Thank you for fixing this issue!
