### ISSUE TITLE
A slip error in the Log_Tests.cls

### ISSUE THREAD

**Issue by harryheart** [trailheadapps/apex-recipes#401]
https://github.com/trailheadapps/apex-recipes/blob/7d754ce9f56ebb2e6cad16078437c6714a1b7560/force-app/tests/Shared%20Code/Log_Tests.cls#L70

In the code above, the error message should be "Expected to find 4 records" instead of "Expected to find 3 records".

**Comment by pozil** [comment]
Good catch, thanks for letting us know. I pushed a fix.
