### ISSUE TITLE
Update NamedCredentials using Connect.API

### ISSUE THREAD

**Issue by pavankumar9849** [trailheadapps/apex-recipes#534]
Hi ,
 I am a new Bee  to salesforce , I am not able to get an idea on how to implement a code to update my calloutURL of NamedCredential for my salesforce org using the connect API. 
I heard that this is a new extensible from 23 onwards , Please share any code samples or any tutorials how can I update .

Thanks in Advance!

**Comment by pavankumar9849** [comment]
Nobody is there to answer my question?

**Comment by Suga-Agustd** [comment]
Can you elaborate the specifics of this issue a bit more?

**Comment by msrivastav13** [comment]
@pavankumar9849 Sorry for delayed response. You can use the below to update an endpoint

https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NamedCredentials_static_methods.htm#apex_ConnectAPI_NamedCredentials_patchCredential_4

We will have recipes for it soon. For now you can also get the NamedCredentialRecipes here 

https://github.com/trailheadapps/apex-recipes/blob/main/force-app/main/default/classes/Integration%20Recipes/NamedCredentialRecipes.cls
