### ISSUE TITLE
Package ApexRecipes Install Failed

### ISSUE THREAD

**Issue by sfdcschwabe** [trailheadapps/apex-recipes#57]
### Summary

Package ApexRecipes Install Failed

### Steps To Reproduce:

I've tried to install the unlocked package 'Apex Recipes' (for admins) with this link: 'https://test.salesforce.com/packaging/installPackage.apexp?p0=04t3g000000kiDJAAY' on one of our sandboxes.

My Domain is registered and deployed

### Expected result

Package installation with errors.

### Actual result

Organization: Colliers International Deutschland GmbH (00D0E0000002LcN)
User: Christian Schwabe (0050O000009pHg3)
Package: ApexRecipes (04t3g000000kiDJ)
Error Number: 752431791-1832068 (1903002296)
Problem:

Permission Read Account depends on permission(s): Read Contact
Provides_Edit_Access_to_Accounts_Except_ShippingStreet: Permission Read Account depends on permission(s): Read Contact

Permission Read Account depends on permission(s): Read Contact
Provides_Read_Only_Access_to_Account_and_All_Fields: Permission Read Account depends on permission(s): Read Contact

Permission Read Account depends on permission(s): Read Contact
Proving_With_Security_Enforced_Works: Permission Read Account depends on permission(s): Read Contact
### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by codefriar** [comment]
@sfdcschwabe - are you still having this issue? We've had a few package releases since early dec, wanted to double check

**Comment by sfdcschwabe** [comment]
On a new developer sandbox I get the following error:

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: --- Keine Auswahl --- (00D09000006Jt2w)
User: Christian Schwabe (00509000002ZgNp)
Package: ApexRecipes (04t3g000000kiK0)

Problem:

1.  Apex compile failure
Apex class ViewService: line 51, column 48: Method does not exist or incorrect signature: void request(NULL, NULL, Map<String,String>, String, NULL) from the type RestClient

**Comment by codefriar** [comment]
Hmm. That’s really weird. And you’re doing the package install? Not the scratch org install?

**Comment by sfdcschwabe** [comment]
Yes.

**Comment by sfdcschwabe** [comment]
To be honest with you, I think the last error is self-inflicted and a problem in my developer org and has nothing to do with the package itself. I can't recreate the installation of the package on our environments either, as I have decoupled parts of Apex classes from the unmanaged package and now use them myself. For this reason alone, reinstalling the unmanaged package would already fail. Since the error is not reproducible form my side, I think the issue can be closed again.
