### ISSUE TITLE
Error deploying with CLI - Fields not found

### ISSUE THREAD

**Issue by guivlm** [trailheadapps/apex-recipes#9]
![Screen Shot 2020-10-14 at 16 33 55](https://user-images.githubusercontent.com/20449025/96036613-1601ad00-0e3b-11eb-91f4-f5eee8c4abc6.png)

**Comment by aaronmattern** [comment]
Try replacing the permission set metadata files with these two.

[PermissionSetMetadata.zip](https://github.com/trailheadapps/apex-recipes/files/5380634/PermissionSetMetadata.zip)

**Comment by guivlm** [comment]
> Try replacing the permission set metadata files with these two.
> 
> [PermissionSetMetadata.zip](https://github.com/trailheadapps/apex-recipes/files/5380634/PermissionSetMetadata.zip)

This replacement solved the issue and was able to deploy.

**Comment by codefriar** [comment]
@guivlm I recommend using Apex Recipes in a scratch org, but there is a pr #10 awaiting review to handle this. You'll still face the regex issue if you install Apex Recipes in an org that has pre-existing classes.
