### ISSUE TITLE
Error retrieving data Regex too complicated

### ISSUE THREAD

**Issue by anilshivaraj** [trailheadapps/apex-recipes#97]
### Summary

Getting Error on screen load "Error retrieving data Regex too complicated"

### Steps To Reproduce:

1.  Follow the installation steps mentioned in the readme

### Expected result
Should see the apex recipe app 

### Actual result
I am recieving an error on screen load that the Regex is too complicated.
Class : `ApexClassUtilities`
Method : `getGroupFromClassBody`
is failing with the exception `FATAL_ERROR Class.ApexClassUtilities.getGroupFromClassBody: line 24, column 1`
### Additional information

![Capture](https://user-images.githubusercontent.com/5904682/108615332-8fe90a80-73c8-11eb-9e7b-3d6e95175763.PNG)
![Capture](https://user-images.githubusercontent.com/5904682/108615340-a0998080-73c8-11eb-8985-11fb4229aace.PNG)

**Comment by codefriar** [comment]
Anil,

This typically happens when you install apex recipes in an org that has other non-apex-recipes code in it. Did you install apex recipes in a brand new scratch org or dev org?

**Comment by anilshivaraj** [comment]
thanks for the quick response Kevin, yes i installed it in my existing dev org and not a new scratch org - didnt know of this limitation thanks for that. Will go ahead and try it in the scratch org.
Just curious - why does the regex fail if there are other apps?

**Comment by codefriar** [comment]
> thanks for the quick response Kevin, yes i installed it in my existing dev org and not a new scratch org - didnt know of this limitation thanks for that. Will go ahead and try it in the scratch org.
> Just curious - why does the regex fail if there are other apps?

It's looking for a very specific set of things at the very beginning of the file - the regex is used to extract related files that should also be loaded in the UI. When that initial comment isn't at the beginning of the class, it has to scan the entire class, and often those classes are simply too-long for the regex.
