### ISSUE TITLE
Logging Framework - Publish Immediate PE Limit not used

### ISSUE THREAD

**Issue by vbhasker** [trailheadapps/apex-recipes#98]
The logging framework built in the recipes is still using the DML limit vs a separate limit for the Publish Immediate (can be verified through Limits.getPublishImmediateDML() and getDMLStatements()). 

The issue seems to be related to the event method returning generic SObject. Instead of returning the direct Platform Event.
```Apex
public SObject toEvent() {
        return new Log__e(
            Log_Message__c = this.message,
            Request_Id__c = this.requestId,
            Quiddity__c = this.quiddity?.name(),
            Severity__c = this.severity?.name()
        );
    }
```
Instead of returning SObject, if this method returned Log__e. A separate limit for Publish Immediate DML limit is used. This seems to be a limitation and a workaround. Hope this helps anyone who is working on a logging framework.

```Apex
public Log__e toEvent() {
        return new Log__e(
            Log_Message__c = this.message,
            Request_Id__c = this.requestId,
            Quiddity__c = this.quiddity?.name(),
            Severity__c = this.severity?.name()
        );
    }
```

**Comment by codefriar** [comment]
@vbhasker - Wow, thank you for such a detailed and precise bug report. 

I'm on it!

**Comment by vbhasker** [comment]
Thank you @codefriar !
